### ISSUE TITLE
Could you indicate the wiring?

### ISSUE THREAD

**Issue by davidxgames** [nopjne/drmdmp64_mass#2]
I am building drmdmp64_mass but I don't understand how to connect it, this is the code
#define N64_EEPROM_DAT (16)
#define N64_EEPROM_CLK (17)
#define N64_WRITE (18)
#define N64_READ (19)
#define N64_CIC_DCLK (20)
#define N64_CIC_DIO (21)
#define N64_COLD_RESET (22)
#define N64_ALEL (27)
#define N64_ALEH (28)
Should I connect this way? because in the images it looks different.

**Comment by nopjne** [comment]
Those pinouts are correct.

Please refer to the DreamDumper64 gerber files by khill, for the connection diagram and board. The link is mentioned in the readme of this project.

Here are 3 additions to the gerber:
Uart TX and RX are repurposed for eeprom data and clk. Eeprom data needs a pullup resistor. And if using a weact pico the 3v3_en and 3v3 need to be joined. I havent tested with a regular Pico.
