### ISSUE TITLE
Can I use normal RP2040 Pico for DreamDumper64 ?

### ISSUE THREAD

**Issue by kirk33** [nopjne/drmdmp64_mass#3]
I use normal RP2040 Pico. It is not work. It don't emulate a drive. I must use WeAct Pico ? Thanks.

**Comment by nopjne** [comment]
I have not attempted with anything else than a WeAct pico. But there are a plethora of pico clones, so make sure the gpio pins correlate to the expected pins.

**Comment by nopjne** [comment]
Software support for the pi-pico has been added.

https://github.com/nopjne/drmdmp64_mass/commit/90b69386f2d610c07a21e37f9b3b8d23ff626cf0
