### ISSUE TITLE
PI Pico Support?

### ISSUE THREAD

**Issue by Mudkipaway** [nopjne/drmdmp64_mass#4]
I have assembled a board with a Raspberry pi pico and flashed the firmware provided but it does not show up when plugged in.

![IMG_20240401_141442281_HDR](https://github.com/nopjne/drmdmp64_mass/assets/149080767/d0778da3-15e1-465a-9191-fd1c6741fdc3)
![IMG_20240401_141454527](https://github.com/nopjne/drmdmp64_mass/assets/149080767/606bbd9e-1605-4887-b9f9-e583d3ab2785)

**Comment by Mudkipaway** [comment]
I was looking for the Weact pico board when i originally purchased the board but did not know where to find it.
Ill try cleaning the board first before seeing if i can find the right thing.

**Comment by nopjne** [comment]
Software support for the pi-pico has been added.
